server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.105.226.190:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: hollyipcc!qaZ
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.cn.entity
  mapper-locations: classpath:mapping/*Mapper.xml
  type-handlers-package: com.cn.jsonConfig

#showsql
logging:
  level:
    cn:
      mark:
        demo:
          mapper: debug

jobs:
  fixedDelay: 5000
  cron: 0/5 * *  * * ?
